{"stability":{"unstable":"ðŸ”¬ This is a nightly-only experimental API.  (allocator_api #32838)"},"apiName":"std::alloc::AllocErr","apiType":"struct","apiDocumentation":{"apiDescription":["The AllocErr error indicates an allocation failure that may be due to resource exhaustion or to something wrong when combining the given input arguments with this allocator."]},"trait implementations":[{"name":"impl std::clone::Clone for std::alloc::AllocErr","stable since":"1.0.0"},{"name":"impl std::fmt::Debug for std::alloc::AllocErr","stable since":"1.0.0"},{"name":"impl std::cmp::Eq for std::alloc::AllocErr","stable since":"1.0.0"},{"name":"impl std::cmp::PartialEq<std::alloc::AllocErr> for std::alloc::AllocErr","stable since":"1.0.0"},{"name":"impl std::fmt::Display for std::alloc::AllocErr","stable since":"1.0.0"},{"name":"impl std::convert::From<std::alloc::AllocErr> for std::collections::CollectionAllocErr","stable since":"1.0.0"},{"name":"impl std::error::Error for std::alloc::AllocErr","stable since":"1.0.0"},{"name":"impl std::marker::Send for std::alloc::AllocErr","stable since":"1.0.0"},{"name":"impl std::marker::Sync for std::alloc::AllocErr","stable since":"1.0.0"}]}