{"stability":{"unstable":"ðŸ”¬ This is a nightly-only experimental API.  (core_intrinsics)intrinsics are unlikely to ever be stabilized, instead they should be used through stabilized interfaces in the rest of the standard library\n"},"apiName":"std::intrinsics::try","apiType":"function","apiDocumentation":{"apiDescription":["Rust's \"try catch\" construct which invokes the function pointer f with the data pointer data.","The third pointer is a target-specific data pointer which is filled in with the specifics of the exception that occurred. For examples on Unix platforms this is a *mut *mut T which is filled in by the compiler and on MSVC it's *mut [usize; 2]. For more information see the compiler's source as well as std's catch implementation."]}}