{"create_time":"2025-04-05T07:01:59.671Z","id":"4ffcbf49-9069-45d5-81c5-3dc73bf87e75","source_url":"file:///C:/Users/Dj/.rustup/toolchains/1.10-x86_64-pc-windows-msvc/share/doc/rust/html/std/io/enum.ErrorKind.html","relations":["description","implements","is_part_of","is_variant_of"],"add_triples":[{"triples":[["std::io::ErrorKind","is_part_of","std::io"],["std::io::ErrorKind","description","A list specifying general categories of I/O error."],["std::io::ErrorKind::NotFound","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::NotFound","description","An entity was not found, often a file."],["std::io::ErrorKind::PermissionDenied","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::PermissionDenied","description","The operation lacked the necessary privileges to complete."],["std::io::ErrorKind::ConnectionRefused","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::ConnectionRefused","description","The connection was refused by the remote server."],["std::io::ErrorKind::ConnectionReset","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::ConnectionReset","description","The connection was reset by the remote server."],["std::io::ErrorKind::ConnectionAborted","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::ConnectionAborted","description","The connection was aborted (terminated) by the remote server."],["std::io::ErrorKind::NotConnected","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::NotConnected","description","The network operation failed because it was not connected yet."],["std::io::ErrorKind::AddrInUse","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::AddrInUse","description","A socket address could not be bound because the address is already in use elsewhere."],["std::io::ErrorKind::AddrNotAvailable","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::AddrNotAvailable","description","A nonexistent interface was requested or the requested address was not local."],["std::io::ErrorKind::BrokenPipe","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::BrokenPipe","description","The operation failed because a pipe was closed."],["std::io::ErrorKind::AlreadyExists","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::AlreadyExists","description","An entity already exists, often a file."],["std::io::ErrorKind::WouldBlock","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::WouldBlock","description","The operation needs to block to complete, but the blocking operation was requested to not occur."],["std::io::ErrorKind::InvalidInput","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::InvalidInput","description","A parameter was incorrect."],["std::io::ErrorKind::InvalidData","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::InvalidData","description","Data not valid for the operation were encountered. Unlike InvalidInput, this typically means that the operation parameters were valid, however the error was caused by malformed input data. For example, a function that reads a file into a string will error with InvalidData if the file's contents are not valid UTF-8."],["std::io::ErrorKind::TimedOut","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::TimedOut","description","The I/O operation's timeout expired, causing it to be canceled."],["std::io::ErrorKind::WriteZero","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::WriteZero","description","An error returned when an operation could not be completed because a call to write returned Ok(0). This typically means that an operation could only succeed if it wrote a particular number of bytes but only a smaller number of bytes could be written."],["std::io::ErrorKind::Interrupted","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::Interrupted","description","This operation was interrupted. Interrupted operations can typically be retried."],["std::io::ErrorKind::Other","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::Other","description","Any I/O error not part of this list."],["std::io::ErrorKind::UnexpectedEof","is_variant_of","std::io::ErrorKind"],["std::io::ErrorKind::UnexpectedEof","description","An error returned when an operation could not be completed because an end of file was reached prematurely. This typically means that an operation could only succeed if it read a particular number of bytes but only a smaller number of bytes could be read."],["std::io::ErrorKind","implements","std::fmt::Debug"],["std::io::ErrorKind","implements","std::clone::Clone"],["std::io::ErrorKind","implements","std::cmp::Eq"],["std::io::ErrorKind","implements","std::cmp::PartialEq"],["std::io::ErrorKind","implements","std::marker::Copy"]],"startIndex":0,"endIndex":39000}],"metrics":{"escapeCount":0,"costTime":245788,"totalUsage":{"prompt_tokens":5407,"completion_tokens":7023,"cached_tokens":0,"reasoning_tokens":5722},"chunkLength":1,"chunksInfo":[{"contextLength":0,"contentLength":17120,"costTime":245788}]},"model":"deepseek-r1-250120","extraInfo":{}}